"""empty message

Revision ID: 567b54a4e9cd
Revises: 3a78fc429592
Create Date: 2024-01-23 22:06:37.910996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '567b54a4e9cd'
down_revision = '3a78fc429592'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
